### ISSUE TITLE
Bug: This site is not secure.

### ISSUE THREAD

**Issue by QinxinTian** [acarcher/VCML#47]
<img width="1062" alt="2017-11-06 7 26 06" src="https://user-images.githubusercontent.com/25886116/32441084-e874c0cc-c2c3-11e7-9058-641df583f0f3.png">
This is a really impressive project, well done. But I found it is not secure.
If it is secure, then the left hand side of the address should be green.

**Comment by hoenn321** [comment]
Fixed issue! Thanks for bringing this up.
